### ISSUE TITLE
Request for Open-Source License

### ISSUE THREAD

**Issue by MiguelMarcelino** [itsDaiton/business-website-template#4]
Hello!

I really enjoyed the structure of this project and found it very well-organized. I was wondering if you might consider adding an open-source license to it? I’d love to use it as a base for a personal website, but of course, I’d like to respect any permissions you set.

Thank you for your time, and thanks for sharing such a great project!

**Comment by itsDaiton** [comment]
Added MIT License. But as stated in the readme of the project, it is a repo based on a video tutorial, so you can check that out as well if you like.

**Comment by MiguelMarcelino** [comment]
Thank you! 
I will check out the video as well.
